# Generated by Django 5.0 on 2023-12-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers_statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='user',
            new_name='profile',
        ),
    ]
