# Generated by Django 5.0 on 2023-12-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
        ('influencers_statistic', '0002_rename_user_statistics_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='influencers.baseprofile'),
        ),
    ]
