# Generated by Django 5.0 on 2023-12-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers_statistic', '0003_alter_statistics_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='profile_pictures_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
