# Generated by Django 4.2.9 on 2024-03-26 21:07

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("influencers_statistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="statistics",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
