# Generated by Django 4.2.9 on 2024-03-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("influencers_statistic", "0002_alter_statistics_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="statistics",
            managers=[],
        ),
    ]
