version: '3'
services:
  web:
    build: .
    command: /bin/bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app/
      - media_volume:/app/media
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379


  worker:
    build: .
    command: celery -A meta_statistic worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A meta_statistic beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  media_volume:



